version: "3" #version of compose
services: # containers are listed under services
  api: # name of python container
    build: . # build custom image with dockerfile in current directory
    depends_on:
      - postgres # postgres container should be set up first
    ports:
      - 8000:8000
    volumes:
    # sync local folder (./ current directory) with folder in container (/usr/src/app), so changes are automatically deployed. 
    # Cotainer can not change files (ro)
      - ./:/usr/src/app:ro
    command: uvicorn app.main.app --host 0.0.0.0 --port 8000 --reload # overwrite command from Dockerfile
    # env_file: # files with environment variables
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres # IP adresse of postgres container
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=Postgress22
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
  
  postgres: # name of postgres container
    image: postgres # pre defined image
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data # path in container that postgres will write to
volumes:
  postgres-db: